#!/bin/sh
BACKUP_PATH="/mnt/pve/Backup/Server/"
BACKUP_FILE="srvoffice1"
KEEP_DAYS=180
PVE_BACKUP_SET="/etc/ /var/lib/pve-cluster/ /root/ /var/spool/cron/ /usr/share/kvm/"
PVE_CUSTOM_BACKUP_SET=""

tar -czf $BACKUP_PATH$BACKUP_FILE-$(date +%Y_%m_%d-%H_%M_%S).tar.gz --absolute-names $PVE_BACKUP_SET $PVE_CUSTOM_BACKUP_SET
find $BACKUP_PATH$BACKUP_FILE-* -mindepth 0 -maxdepth 0 -depth -mtime +$KEEP_DAYS -delete
